---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: sync
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./addons/sync
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  postBuild:
      substituteFrom:
        - kind: ConfigMap
          name: cluster-info
  dependsOn:
  - name: flux-system
