apiVersion: v1
kind: ConfigMap
metadata:
  name: wkp-addon
data:
  wkp.yaml: |
    ---
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: wkp-deployment-job
    spec:
      template:
        spec:
          containers:
            - name: wkp-components
              image: docker.io/weaveworks/wks-components-track-preview:0.0.25
              volumeMounts:
                - name: wkp-config
                  mountPath: /root/.wks
                - name: wkp-creds
                  mountPath: /root/creds
              command: ["/bin/bash"]
              args:
              - -c
              - /deploy-wkp.sh
              env:
                - name: GITHUB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: wkp-creds
                      key: GITHUB_TOKEN
                - name: CLUSTER_NAME
                  valueFrom:
                    configMapKeyRef:
                      name: cluster-info
                      namespace: kube-system
                      key: cluster_name
          restartPolicy: Never
          volumes:
            - name: dockerhub-password
              secret:
                secretName: dockerhub-password
            - name: wkpconfig
              configMap:
                name: wkp-configuration
                items:
                  - key: weaveworks.entitlements
                    path: weaveworks.entitlements-enc
                  - key: wkp-setup-config
                    path: config.yaml
      backoffLimit: 4
