apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: wkp-config
  namespace: tenants
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./apps/wkp/config
  prune: true
  validation: client
  targetNamespace: tenants
  postBuild:
    substitute:
      cluster_name: "tenant01"
      cluster_region: "eu-north-1"
      git_org: "wkp-capi-demo"