---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: config
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./config
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-config
  validation: client
