---
apiVersion: cluster.x-k8s.io/v1alpha4
kind: Cluster
metadata:
  name: my-cluster
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
    kind: AWSManagedControlPlane
    name: my-cluster-control-plane
  infrastructureRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
    kind: AWSManagedControlPlane
    name: my-cluster-control-plane
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
kind: AWSManagedControlPlane
metadata:
  name: my-cluster-control-plane
  namespace: default
spec:
  region: eu-west-1
  sshKeyName: paul
  version: v1.21.4
---
apiVersion: cluster.x-k8s.io/v1alpha4
kind: MachinePool
metadata:
  name: my-cluster-pool-0
  namespace: default
spec:
  clusterName: my-cluster
  replicas: 0
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: my-cluster
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
        kind: AWSManagedMachinePool
        name: my-cluster-pool-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: AWSManagedMachinePool
metadata:
  name: my-cluster-pool-0
  namespace: default
spec: {}