apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: account-creds
  namespace: account-one
spec:
  encryptedData:
    AccessKeyID: AgBEgv7RPm95lTGW67E5ewFLPJByGZCHxrJwXjgBNsuRHChAMMtsaEJNYBX3GE20KvW1xRDqqqix+uP8GtyVlIwhhBz3qKYElLXL5A9GN3Zsro3jAQPTXVxc2Il+yG781en2rNZ1ypj0/siJVYHsWoBpNDCq+e/UVpBQWnRX1/fLG+6SNpSwVOMVDMH+wPtU3jz2vnBWhJAW0IdpV/GkeX+bf3Ac/0Uz3TSNSRNWGJvP36rH7gA49FGoTSNazDhfJHAiNtedLsXK5sW9hlcLGrR8RBXgcVtbTUW0SNZOKud8MtAKdnybSsQpx7bip0c5kvQyGwZgs1PUJ8SwAtkrMXvPai/I63D1BDtc7Xcr2k0RG8ZVY/4WrLiihGyrZL1lD7cZmSbVNomFav84hZpmlsY4ShndVsvD0DNGDOC+V0q3jr26uGIXOA4u96/vq9LVy+QpLANniyjXDraIzkJMHJPP+uXVSCFO3s+0fNeovymT+dhAfNltcbvZ4T+H68gdW2LlY+OW+xKwmNCt9Jv2E9e9qFHcXYti/mK+2GguiaBeJN1I3XiiHnLFICPAx9CeDnLlyyWtP94LrvtYtRXMwW8fmHehPMNFJHp/zGGwblOx7BQI3vIDNuU105NMZpmjM8MdUXDc/kieAhqepFT+jK9+wF+iT1LLkh7RMTeZ4KultQYoiSc0ES+ozrkzZMKUwxjKkGR0sPUe3+XZIlllAHz6pYumAA==
    SecretAccessKey: AgC44MykFp5tdWdt1xKXvrL49TQHTdGslzqBXNJCxg5Ne4bLeDUlTvf79lfnwaJ3RRp1+poYbokQcYXuq0hCfoi8kxWjRrun9Fg1FYypJQmei8RdVW5ieF5dfSP9hFcaMs7geb+hsZ3O/6aEvTlMGR1iL12kPgj89M2h05P7EijFKbIorjUaHcVCKwEn9EzySkCYHkdMvfVp3lZQrhq0NK653qgVOpK9MDpjvuzBReh2IcebmOicnSkXF8IypXGSHvv5yaJ1PxpE21SCBLvHldXqL4WSBB1znUCdwHNLR9HKV6QsHOzNwOtYDQgLAUhJKypjHMe8oi/uKft1gEMuuY2Zq8Q0t/E/2VI8QFUmVr1CjWbK/I3RXHK1MGHiBJjSMrq44ZgthlHkv//RqIA2r0Xh3DacEZVJ9aaLMcEZQX0Xcb1seHGBRLCuSIB3Xi1uXTgeGlM+JYfOk+TBuayfnw3Tccmd1WWDx4Uc0WW6l/1PDDyoy9a5WcvUFkAbz5Mjx/6FYfT8BvlOzvb/8qQ+4MxQlvR1RJ6gTXWLPeLeCeuMyHNX3xZy/3E49ZaaDcprknFVXJbp3yPDPGJJ2wVY5LwTQSFvP4re0f93NahEc5fUyQDEM4TJri9Af5Zde/ixLcb+WKj+hK7jDA8L4w24t+Ew+RpNcNUp7GQtb5AbgtEoF8gmJo09RvoJ6SSnCaJ6FtTuhLCMgHBQArx1Bz0FKYPB3exmlzJh20a5r9BRiZBPy2s0Owj0rUrU
  template:
    metadata:
      creationTimestamp: null
      name: account-creds
      namespace: account-one

