---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./addons/sealed-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client

