---
apiVersion: v1
kind: Namespace
metadata:
  name: "account-cx"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSClusterStaticIdentity
metadata:
  name: "account-cx-account"
spec:
  secretRef:
    name: account-creds
    namespace: account-cx
  allowedNamespaces:
    selector:
      matchLabels:
        cluster.x-k8s.io/ns: "account-cx"
